server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_jxc
    username: root
    password: 11
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false